owner: HephX
repo: salitech-status

sites:
  - name: Salitech Website
    url: https://salitech.de

  - name: Salitech Dashboard
    url: https://app.salitech.de

  - name: Automation
    url: https://automation.salitech.de

  - name: Analytics
    url: https://analytics.salitech.de

status-website:
  cname: status.salitech.de
  name: Salitech Status
  introTitle: "Salitech System Status"
  introMessage: "Aktueller Betriebsstatus der Salitech-Dienste."

  navbar:
    - title: Status
      href: /
    - title: Salitech
      href: https://salitech.de
